### ISSUE TITLE
Merging upstream

### ISSUE THREAD

**Issue by danse** [stackbuilders/datetime#3]
Thanks for doing this. At the same time, i think that the clean solution would be to just update `datetime` on Hackage with this code. Any plans to do it in the future?

**Comment by jpvillaisaza** [comment]
@danse I think that was the idea at first, but [datetime](http://hackage.haskell.org/package/datetime) was last uploaded April 2011 and the GitHub repository no longer exists.

**Comment by danse** [comment]
Right. I think that in this case you should be allowed to publish a new version of `datetime`, becoming the new maintainers

**Comment by danse** [comment]
Here is the [relevant section in the Hackage doc](https://wiki.haskell.org/Taking_over_a_package)

**Comment by jpvillaisaza** [comment]
@danse Thank you very much for the link.

We'll try to contact @esessoms or @jdevelop ([maintainers for datetime](http://hackage.haskell.org/package/datetime/maintainers/)), and update this issue.

**Comment by danse** [comment]
cool, thanks to you for following up on this! :sunglasses:

**Comment by jdevelop** [comment]
what's up, again? I'm a bit surprised that I'm the maintainer of Datetime :)

**Comment by jpvillaisaza** [comment]
@jdevelop Ha, ha, :) Is there a repository for this package right now? @jsl made some changes in May to make it build with GHC 7.10, but the repository listed in Hackage (http://github.com/esessoms/datetime) no longer exists, and that's the reason for this fork and the datetime-sb package. Thanks.

**Comment by jdevelop** [comment]
I don't have the repo either, I probably picked the sources from the former one and pushed to hackage. That was long time ago :) So it's fine if you could use this one as a primary source.

**Comment by jpvillaisaza** [comment]
@jdevelop Great, that sounds good. Do you want to upload the package or can you add us as maintainers in Hackage (either jsl or jpvillaisaza or stackbuilders). I'll add an issue to update the Cabal configuration to make it datetime, not datetime-db.

**Comment by jpvillaisaza** [comment]
@danse Thanks again for opening this issue. We'll close it once this repository replaces the one listed in Hackage right now.

**Comment by jdevelop** [comment]
Sure thing I can upload stuff, but I wonder how to add maintainers and the appropriate access to Cabal

**Comment by jpvillaisaza** [comment]
@jdevelop You can add maintainers in http://hackage.haskell.org/package/datetime/maintainers/edit.

**Comment by jdevelop** [comment]
added all of mentioned users. Pls let me know that it works, so I will remove myself from the list.

**Comment by jpvillaisaza** [comment]
@jdevelop Thank you, I'll let you know as soon as we upload a new version.

**Comment by jpvillaisaza** [comment]
@jdevelop Thank you again. It worked, I uploaded version 0.3.0 and changed the GitHub repository to this one.

**Comment by jpvillaisaza** [comment]
@danse Thanks again. As of version http://hackage.haskell.org/package/datetime-0.3.0 this is the repository for datetime.

**Comment by danse** [comment]
Whoohoo! Well done folks!
