### ISSUE TITLE
addSecond 1 (2014/11/10 00:09:00) = 2014/11/10 00:09:59

### ISSUE THREAD

**Issue by notogawa** [stackbuilders/datetime#8]
Is this behavior intended ?

```
*Data.DateTime> let x = fromGregorian 2014 11 10 0 9 0
*Data.DateTime> x
2014-11-10 00:09:00 UTC
*Data.DateTime> addMinutes 1 x
2014-11-10 00:09:59 UTC
```

**Comment by jpvillaisaza** [comment]
@notogawa No, it's a bug, than you very much for reporting it.

I think both `addMinutes` and `addSeconds` are wrong, which is probably related to `toSeconds` being wrong as well.

**Comment by int-e** [comment]
I think `toSeconds` should just stick to `Rational` (currently it converts the result of `toMJD dt - startOfTimeMJD` to `Double`, thereby inviting rounding issues as the above):

    toSeconds dt = floor $ 86400 * (toMJD dt - startOfTimeMJD)

**Comment by Centeno448** [comment]
Closing because library is being deprecated.
